### ISSUE TITLE
Muito Útil

### ISSUE THREAD

**Issue by idespindola** [georgevbsantiago/qsacnpj#1]
A taxa de transmissão do arquivo original da RFB é muito baixa. O tratamento e armazenamento dos dados em sqlite é muito útil para consulta de grande volume de dados. Agradeço a disponibilização do link para download dos dados devidamente estruturados e de fonte confiável. 

Enalteço os esforços da comunidade Dados Abertos BR para que essa e outras bases de dados sejam disponibilizadas à sociedade e atualizadas periodicamente.

**Comment by georgevbsantiago** [comment]
Olá, @idespindola .
Muito obrigado pelo feedback.

A título de curiosidade, em qual tipo de atividade você tem utilizado a base de dados do CNPJ?

**Comment by idespindola** [comment]
Prezado @geogevbsantiago ,

Utilizo a base para análise das empresas de um município. Análise das baixas e evações para outro municípios. Identifico ramos de atividades, empresas optantes pelo simples nacional ou simei. E situações cadastrais.

**Comment by AndySchmitt** [comment]
A disponibilização (e atualização) desta base me economizou um trabalho enorme. Gostaria de agradecer aos envolvidos. Disponibilizem um botão do paypal para que eu possa fazer uma doação!

**Comment by georgevbsantiago** [comment]
Olá, @AndySchmitt 
Fico feliz que a disponibilização da base de dados tenha ajudado. 
Em relação ao link para doação, essa é uma questão que iremos refletir e amadurecer. Muito obrigado!

**Comment by georgevbsantiago** [comment]
@idespindola  e @AndySchmitt 

Se não for incômodo, vocês poderiam registrar como usam a base de dados do CNPJ no tópico que criei: https://github.com/georgevbsantiago/qsacnpj/issues/4

Seria muito importante consolidar os depoimentos. Abs
