### ISSUE TITLE
Dúvida - Como conectar o script com SQLite, MS SQL Server, Oracle e MySQL

### ISSUE THREAD

**Issue by rtheodoro** [georgevbsantiago/qsacnpj#10]
Olá !

Lendo o README, reparei nesta parte:

1.2 - Reformulado o código para conexão com os SGBDs. Agora, é possível conectar o script com SQLite, MS SQL Server, Oracle e MySQL. Os desenvolvedores conseguirão também implementar a conexão com outros SGBDs.

Como meu objetivo é tratar os dados com o pacote e subir para postgreSQL, fiquei curioso. 

Como funcionaria esta conexão? Poderia dar um exemplo?

Obrigado!

**Comment by georgevbsantiago** [comment]
Olá, veja o conjunto de material disponibilizado em https://db.rstudio.com/
Lá, há muitas informações de como realizar a configuração das conexões.
A função da conexão com o banco de dados a ser configurada está no arquivo "082_connect_sgbd.R"
