### ISSUE TITLE
Link do arquivo CSV quebrado

### ISSUE THREAD

**Issue by cezarpretto** [georgevbsantiago/qsacnpj#11]
No arquivo readme o link para download dos arquivos em CSV da última atualização está quebrado. Poderia atualizar com o link correto? 

Obrigado!

**Comment by georgevbsantiago** [comment]
Problema resolvido. Obrigado por avisar.

**Comment by cezarpretto** [comment]
Obrigado amigo!



Em sex., 28 de fev. de 2020 às 18:10, George Santiago <
notifications@github.com> escreveu:
