### ISSUE TITLE
Coluna "tipo_atualizacao" da "cnpj_dados_cnae_secundario" está como NA

### ISSUE THREAD

**Issue by rtheodoro** [georgevbsantiago/qsacnpj#12]
Olá!

A coluna "tipo_atualizacao" da tabela "cnpj_dados_cnae_secundario" está como _NA_ em todas as linhas.

Isto é normal ?

Obrigado.

**Comment by georgevbsantiago** [comment]
Olá,

Segundo as informações disponibilizadas no dicionário de dados da Receita Federal, essa coluna fica em Branco quando a carga é classificada como FULL (você verá um F na coluna 'indicador').

![image](https://user-images.githubusercontent.com/22058152/75797134-72ec9f00-5d53-11ea-8f42-76831245af82.png)
