### ISSUE TITLE
Atualização das base de dados SQL Lite

### ISSUE THREAD

**Issue by joao-wivo** [georgevbsantiago/qsacnpj#13]
Boa tarde, primeiramente parabéns pelo projeto, a base de dados gerada é extremamente útil!

Acabei de ver que a base de dados no site da receita foi atualizada recentemente, algum previsão de atualização da base de dados no formato SQL Lite ?

Obrigado pela ajuda e continue com o projeto pois ele é ótimo!

**Comment by georgevbsantiago** [comment]
Olá, acabamos de realizar a atualização e disponibilizamos os dados em SQLite. Amanhã, disponibilizaremos o em CSV. Demoramos alguns dias para atualizar os dados, pois o servidor de arquivo da Receita Federal é absurdamente lento para realizar o Download.
