### ISSUE TITLE
Evaluation error: object 'df_qsa_6' not found.

### ISSUE THREAD

**Issue by bralvarenga** [georgevbsantiago/qsacnpj#14]
Olá, George! Primeiro, parabéns pelo excelente trabalho com a base de CNPJs!

Estou com um problema quando vou rodar a sugestão 4, localizar um conjunto de CNPJs e armazená-lo em um csv:

qsacnpj::gerar_bd_cnpj(path_arquivos_txt = "~/Downloads/CNPJ/Dados",
                       localizar_cnpj = c("00000000000191", "07237373000120",
                                          "00360305000104", "04902979000144"),
                       n_lines = 100000,
                       armazenar = "csv")

Usando os próprios CNPJs de exemplo do manual, está dando um erro na leitura do penúltimo arquivo. A execução do código é interrompida no seguinte ponto e com a seguinte mensagem:

22% 1145 MB[1] "Analisando linhas: 900001 a 1000000 - arq: K3241.K03200DV.D00422.L00019"

Error in read_lines_chunked_(ds, locale, na, chunk_size, callback, progress) : 
  Evaluation error: object 'df_qsa_6' not found.

Estou usando os últimos dados disponíveis da Receita, Data de geração do arquivo: 26/04/2020.
Já refiz o download do arquivo 19, achando que poderia ter sido problema no arquivo, mas não resolveu.

Sabe como posso resolver isso?
Obrigado.

**Comment by georgevbsantiago** [comment]
Olá, @bralvarenga 

É bem estranho isso que está acontecendo com você, pois, como relatado, ocorre só no penúltimo arquivo. Não sei se é algum problema nos pacotes R que você utiliza (enfrentei algo parecido em uma versão do pacote `tidyr` ao usar a função `unnest` ou algo envolvendo o encoding do seu sistema operacional.

Para analisar, precisaríamos investigar a versão do R que vocês está usando, a versão dos pacotes o seu sistema operacional...

**Comment by c-conra** [comment]
Oi George,

Parabéns por este trabalho!

@bralvarenga, eu acabei de ter o mesmo problema que você, também no arquivo 19. Eu consegui fazer uma gambiarra que pode funcionar para você também, mas apenas caso você não precise da terceira tabela de CNAEs secundários filtrada para a empresa filtrada. 

Pelo que entendi, o arquivo **df_qsa_6** armazena temporariamente o chunk filtrado da tabela de CNAEs secundários para salva-lo no arquivo "cnpj_dados_cnae_secundario.csv". Se você não precisa saber o CNAE secundário das empresas buscadas, pode simplesmente "silenciar" o salvamento do **df_qsa_6** e assim evitar o erro deste objeto não ser encontrado.

Eu fiz da seguinte forma:

1) Abre o source-code onde o **df_qsa_6** é criado usando a função trace():
**trace("tratar_arquivo_txt", edit=T, where = gerar_bd_cnpj)**

2) Comenta (ou deleta) a linha 127 onde se lê "df_qsa_6 <- dplyr::filter(df_qsa_6, cnpj %in% localizar_cnpj)".

Funcionou para mim.

Abraço,
Conrado

**Comment by c-conra** [comment]
Ah! Mas depois de silenciar a linha 127 eu executei a função **qsacnpj::gerar_bd_cnpj()** apenas nos dois últimos arquivos da Receita Federal (19 e 20). 

Se rodar em todos os 20 arquivos, acho que o tamanho do arquivo "cnpj_dados_cnae_secundario.csv" pode demasiadamente grande uma vez que todas as linhas são repassadas para ele.
