### ISSUE TITLE
Possível erro na tabela tab_cnae

### ISSUE THREAD

**Issue by rsribeiro** [georgevbsantiago/qsacnpj#18]
Baixei os arquivos gerados a partir da base disponibilizada pela RFB em 04/07/2020 e encontrei alguns problemas, que parecem se repetir tanto nos arquivos CSV quanto na base SQLite. Parece estar relacionado com a presença do caractere line_feed ('\n' ou 0x10) dentro de alguns campos de texto. As seguintes consultas, quando executadas dentro do SQLite retornam linhas:

- `select * from tab_cnae where nm_divisao like '%'||char(10)||'%';`
- `select * from tab_cnae where nm_grupo like '%'||char(10)||'%';`
- `select * from tab_cnae where nm_classe like '%'||char(10)||'%';`
- `select * from tab_cnae where nm_cnae like '%'||char(10)||'%';`

Ao abrir o CSV dessa tabela em algum software como o Notepad++ no Windows é possível verificar que esse caractere de quebra de linha interfere no arquivo. Isso também gerou problemas para mim ao exportar um arquivo CSV a partir da base SQLite, pois apareceram quebras de linha em locais errôneos.

Não verifiquei se o problema se repete em outras tabelas.

**Comment by georgevbsantiago** [comment]
Olá, @rsribeiro 

Obrigado por reportar o achado.
Na próxima atualização, acho que dá para corrigir isso aplicando a função `stringr::squish` antes de gravar a base no SQLite.
Vou fazer teste e te respondo
