### ISSUE TITLE
Quantidade reduzida de CNPJs 

### ISSUE THREAD

**Issue by willopinheiro** [georgevbsantiago/qsacnpj#2]
Olá!
Antes de tudo, parabéns pela iniciativa e pela qualidade do código. Ficou show!!!

Fiz o download hoje dos dados de CNPJ (a partir do arquivo CSV único) e verifiquei que constam em torno de 20 milhões de CNPJs. Ocorre que aqui no órgão onde trabalho temos uma base de cnpj adquirida em 12/2017 junto ao SERPRO e nessa base constam 36 milhões de CNPJs.

Sabem explicar essa grande diferença? será que algum tipo de empresa não foi incluída na exportação? ou será que houve algum erro no código q fez com que alguns cnpjs não fossem gerados no cvs?

Se souberem alguma explicação, favor me avisem.

**Comment by georgevbsantiago** [comment]
Olá, @willopinheiro 

Conforme conversamos e registrado também no grupo "Dados Abertos .BR" no Telegram, a suposta inconsistência na quantidade de dados foi gerada pelo código usado pela sua equipe na ora de importar os dados do CSV. 

Como indicado na conversa que tivemos, caso opte por usar o CSV, faça a importação dos dados por partes (chunck), usando funções como a `readr::read_delim_chuncked` ou a `readr::read_lines_chuncked` (acrescido de da função `callback` nos argumentos da função anterior) do pacote `readr`
De outro modo, vocês podem usar a base de dados liberada pelo SQLite para realizar essa importação/exportação de dados.

Atualmente, tendo como referência a base de dados liberada pela Receita Federal em maio de 2019, constam 40.754.938 registros/observações/linhas.

Por fim, cabe precise de mais algum esclarecimento, estamos a disposição.

**Comment by rtheodoro** [comment]
Olá, tudo bem?  Estou tendo o mesmo problema. Mesmo importando por chunks, estou recebendo apenas 26 milhões de linhas. Mesmo tentando fazer filtros. Poderiam me ajudar ? o Código que estou utilizando é este: 

```r
arq_grande <- file("/cnpj_dados_cadastrais_pj.csv", "r")
tam_chunk <- 5000
df1 <- read.csv(arq_grande, nrows = 10, header = T, sep = "#", dec = ".")
for(i in 1:ncol(df1)){df1[,i] <- df1[,i] %>% iconv(from = 'UTF-8', to = 'latin1')}
df_filtrado <- df1 %>% filter(codigo_natureza_juridica == c("2143","2330")) %>%  select(cnpj,everything())
write.table(df_filtrado, "cnpj_dados_cadastrais_pj_filtrado_coop.csv", row.names = F, sep = "#", dec = ".")

nrow <- 1
totalRows <- 0

repeat {
  df <- read.csv(arq_grande, header=FALSE, sep="#", col.names = names(df1), nrows = tam_chunk)
  for(i in 1:ncol(df)){df[,i] <- df[,i] %>% iconv(from = 'UTF-8', to = 'latin1')}
  nRow = nrow(df)
  totalRows <- totalRows + nRow
  cat("Lendo", nrow(df), "linhas, total lido", totalRows, "\n")
  if (nrow(df) == 0)
    break
  df_filtrado <- df %>% filter(codigo_natureza_juridica == c("2143","2330")) %>%  select(cnpj,everything())
  write.table(df_filtrado, "cnpj_dados_cadastrais_pj_filtrado_coop.csv", append = T, col.names = F, row.names = F, sep = "#", dec = ".")
}
close(arq_grande)
```

**Comment by rtheodoro** [comment]
Estou tendo o mesmo problema. Mesmo importando por chunks, ele lê apenas 20.315.814.

Os demais arquivos parecem ser importados corretamente, chegam a 50 milhões de linhas (+/-).

Algo no meu código esta errado? 

```r
arq_grande <- file("cnpj_dados_cadastrais_pj.csv", "r")
tam_chunk <- 3000
df1 <- read.csv(arq_grande, nrows = 10, header = T, sep = "#", dec = ".")
for(i in 1:ncol(df1)){df1[,i] <- df1[,i] %>% iconv(from = 'UTF-8', to = 'latin1')}
df_filtrado <- df1 %>% filter(codigo_natureza_juridica == c("2143","2330")) %>%  select(cnpj,everything())
write.table(df_filtrado, "cnpj_dados_cadastrais_pj_filtrado_coop.csv", row.names = F, sep = "#", dec = ".")

nrow <- 1
totalRows <- 0

repeat {
  df <- read.csv(arq_grande, header=FALSE, sep="#", col.names = names(df1), nrows = tam_chunk)
  for(i in 1:ncol(df)){df[,i] <- df[,i] %>% iconv(from = 'UTF-8', to = 'latin1')}
  nRow = nrow(df)
  totalRows <- totalRows + nRow
  cat("Lendo", nrow(df), "linhas, total lido", totalRows, "\n")
  if (nrow(df) == 0)
    break
  df_filtrado <- df %>% filter(codigo_natureza_juridica == c("2143","2330")) %>%  select(cnpj,everything())
  write.table(df_filtrado, "cnpj_dados_cadastrais_pj_filtrado_coop.csv", append = T, col.names = F, row.names = F, sep = "#", dec = ".")
}
close(arq_grande)
```

Estou precisando disso com urgência e não esta dando certo.
