### ISSUE TITLE
Problema com coluna qualificacao responsavel/socio em diferentes tabelas

### ISSUE THREAD

**Issue by rsribeiro** [georgevbsantiago/qsacnpj#20]
Encontrei um problema para fazer join entre as tabelas usando a coluna `qualificacao_responsavel`. Nas tabelas `cnpj_dados_cadastrais_pj` e `cnpj_dados_socios_pj` as colunas estão sempre com 2 dígitos, com o zero à esquerda quando é o caso.

Na tabela `tab_qualificacao_responsavel_socio` aparecem valores com apenas 1 dígito, sem zero à esquerda.

**Comment by georgevbsantiago** [comment]
Obrigado por reportar. Vou verificar.

**Comment by georgevbsantiago** [comment]
Identifiquei o problema. 
A Receita Federal disponibiliza uma tabela no site ([link do site](https://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj)) ([link da tabela](https://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/tabela-de-qualificacao-do-socio-representante.ods))

Os números entre 1 a 9 na tabela disponibilizada pela Receita Federal estão apenas com 1 dígito.

Vou corrigir essa falha nos dados que a própria Receita Federal disponibiliza na próxima publicação.

Obrigado por reportar mais essa questão.
Se identificar mais problemas, é só abrir as issues.
