### ISSUE TITLE
Nova versão da base tratada

### ISSUE THREAD

**Issue by isaac-souza** [georgevbsantiago/qsacnpj#21]
Percebi que mais ou menos de dois em dois meses uma nova versão processada da base é lançada e o ultimo lançamento ocorreu no mês 09, então teoricamente o próximo lançamento seria esse mês, porém ainda não aconteceu.

Existe previsão para a liberação da próxima versão tratada da base?

Parabéns pelo excelente trabalho, de verdade.

Isaac Souza

**Comment by biutas** [comment]
Acredito que a atualização ocorrerá no inicio de dezembro, pois a ultima atualização foi em 05/09/2020 e a cada 3 meses é atualizada.

**Comment by georgevbsantiago** [comment]
Olá, @isaacsouza17 
A atualização da Base de Dados é trimestral. A Receita Federal libera os dados neste link: https://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj

Assim que os novos dados forem disponibilizados, iremos atualizar.
