### ISSUE TITLE
Base de Dados em CSV de 05/09/20

### ISSUE THREAD

**Issue by fmgoto** [georgevbsantiago/qsacnpj#22]
Oi, George, tudo bem? Parabéns pelo trabalho! Estava baixando os dados direto da RFB qd vi que vc disponibilizou tudo compilado! Me economiza várias horas...

Estou com uma dúvida sobre a base tratada em CSV (https://bit.ly/2GTGHHM). Vc reporta que há 45.153.764 CNPJs, mas encontrei apenas 20.363.178 (CNPJs únicos) no arquivo cnpj_dados_cadastrais_pj.csv. Estou lendo no R, com o read.csv.

Pode haver alguma imprecisão minha, no CSV ou no texto explicativo?

Muito Obrigado, Fabio

**Comment by georgevbsantiago** [comment]
Olá, @fmgoto 

Pelo seu relato, e considerando outros depoimentos do github e do Telegram, você está sofrendo com estouro de memória. Sugiro não usar a função `read.csv`, pois ela não conseguirá alocar todos os dados na sua memória . Tente outras funções do pacote {[vroom](https://github.com/r-lib/vroom)} ou {[data.table](https://github.com/Rdatatable/data.table)} para ler o CSV.

No mais, se puder, deixe o seu depoimento no tópico [Por que uma base de dados do CNPJ é importante para você? ](https://github.com/georgevbsantiago/qsacnpj/issues/4)
Att
