### ISSUE TITLE
Dados atualizados em novembro

### ISSUE THREAD

**Issue by lvftavares** [georgevbsantiago/qsacnpj#24]
Poderia processar os dados disponibilizados em novembro/2020 ? Agradeço !

**Comment by georgevbsantiago** [comment]
Olá, Tive alguns contratempos pessoais no início do ano.
Acredito que publicarei os dados tratados nos próximos dias.

**Comment by rufino-bernardo** [comment]
> 
> 
> Olá, Tive alguns contratempos pessoais no início do ano.
> Acredito que publicarei os dados tratados nos próximos dias.

Alguma previsão de quando teremos os dados dados tratados de Novembro?

Obrigado!

**Comment by georgevbsantiago** [comment]
Já está sendo liberada. Contudo, no repositório há o código em linguagem R para que qualquer pessoa possa realizar o tratamento. Não é a intenção desse repositório garantir e liberar a base de dados tratada, mas sim disponibilizar ferramentas para o acesso aos dados da Receita Federal de forma estruturada por qualquer pessoa.
