### ISSUE TITLE
library_error, não consigo iniciar o tratamento dos dados

### ISSUE THREAD

**Issue by Silvaedoo** [georgevbsantiago/qsacnpj#25]
Erro: Cannot read file D:/CNPJ/R/3/K3241.K032001K.CNPJ.D01120.L00003.txt: boost::interprocess_exception::library_error
sou novato, não entendo oque este erro significa, pode me ajudar?
(tentativas para contornar:  3 reinstalações, mudança de local de arquivo, renomeação de arquivo para nome curto, baixar os dados novamente e rezar pra são Sebastião dos arquivos corrompidos uahsuhasuas )
obs: o arquivo "K3241.K032001K.CNPJ.D01120.L00003.txt", abre em outros editores de texto como Emed e Glogg.

**Comment by georgevbsantiago** [comment]
Olá. Detalhei mais as instruções do README. Leia e tente novamente. Att
