### ISSUE TITLE
Geração das bases com problema

### ISSUE THREAD

**Issue by tutalucena** [georgevbsantiago/qsacnpj#29]
Bom dia pessoal! Parabéns pelo trabalho que foi realizado, caso consigam solucionar o problema do novo layout, este código será muito útil no meu dia a dia. Infelizmente após baixar toda a base da receita e rodar o programa, ele gerou uma base sqllite com menos de 2GB, o que está aparentemente incorreto. Farei um teste no formato CSV porém creio que não dará certo também se o problema está no layout =(

**Comment by rictom** [comment]
Os seguintes projetos funcionam com o layout novo das tabelas da Receita:
https://github.com/rictom/cnpj-sqlite
https://github.com/rictom/cnpj-mysql
https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ
