### ISSUE TITLE
Publicação no Dados Gov BR

### ISSUE THREAD

**Issue by e-ruiz** [georgevbsantiago/qsacnpj#3]
Olá, primeiramente muito obrigado por dedicar(em) um tempo para o tratamento desses dados, e publicar o trabalho para todos! Ótima iniciativa.

Sugestão: publicar, se possível, o fruto desse trabalho no http://dados.gov.br/ visando atingir ainda mais pessoas.

:+1:

**Comment by georgevbsantiago** [comment]
Olá, @e-ruiz , você sabe qual é o procedimento para realizar essa publicação?
Seria interessante, mas não conheço o canal de comunicação oficial do Portal Dados Abertos para realizar essa publicação.

Grato pela sugestão.

**Comment by e-ruiz** [comment]
Também desconheço o procedimento, mas pelo que consegui levantar no portal tens que formatar os dados seguindo algumas regras, se cadastrar no portal e publicar.

Referências
http://dados.gov.br/pagina/contato
http://dados.gov.br/pagina/faq
http://dados.gov.br/pagina/cadastrar-organizacao

:smiley: :+1:
