### ISSUE TITLE
Não estou conseguindo gerar a base em CSV

### ISSUE THREAD

**Issue by rafaelsmelo** [georgevbsantiago/qsacnpj#5]
Prezado George,
Primeiramente, muito obrigado por disponibilizar sua contribuição ela me poupará inúmeras horas.

Atualmente estou com dificuldade ma pacote., o mesmo não está gerando todos os arquivos que deveria criar. 
Ao rodar ele avisa que a "Base de Dados do CNPJ gerada com Sucesso!", contudo só cria 5 arquivos não gerando os `dados_cadastrais_pj`, `dados_socios_pj` e `dados_cnae_secundario_pj`. Você poderia me ajudar?
Estou gerando numa máquina com 24 processadores, 200 Gb ram, 2,39 Ghz, 1Tb de HD (em resumo não é a máquina), através do RStudio 1.2.1335 e R v.3.6.

**Comment by georgevbsantiago** [comment]
Olá, desculpe a demora na resposta. 
Nos próximos dias, a Receita Federal deve estar liberando a atualização da Base de Dados. Assim que a nova base for liberada, farei o teste para verificar se tudo ocorre sem problemas na minha máquia. Contudo, informo que esse problema nunca ocorreu na minha máquina.

**Comment by rtheodoro** [comment]
Comigo estava acontecendo a mesma coisa.
Resolveu quando eu coloquei apenas o caminho do arquivo .txt

qsacnpj::gerar_bd_cnpj(path_arquivos_txt = "D:/qsa_cnpj/",
                       localizar_cnpj = "NAO",
                       n_lines = 10000,
                       armazenar = "csv")

Como sou novo no R, não sei dizer o porque.
