### ISSUE TITLE
Duvidas sobre uma coluna

### ISSUE THREAD

**Issue by tmcarmo** [georgevbsantiago/qsacnpj#6]
Estamos usando a base para levantar algumas informações e fazer alguns cruzamentos de dados e estamos tendo um problema com a coluna **"opcao_pelo_simples"** na tabela de _**CNPJ**_, que está apresentando diversos códigos. Já foi identificado o que significa cada código?
Abçs.
Thiago

**Comment by WanCaSil** [comment]
> Estamos usando a base para levantar algumas informações e fazer alguns cruzamentos de dados e estamos tendo um problema com a coluna **"opcao_pelo_simples"** na tabela de _**CNPJ**_, que está apresentando diversos códigos. Já foi identificado o que significa cada código?
> Abçs.
> Thiago

Thiago, boa tarde. Veja se o abaixo te ajuda...

> INDICADOR DA EXISTÊNCIA DA OPÇÃO PELO SIMPLES
> 0 OU BRANCO - NÃO OPTANTE
> 5 E 7 – OPTANTESPELO SIMPLES
> 6 E 8 – EXCLUÍDO DO SIMPLES

fonte: [http://200.152.38.155/CNPJ/LAYOUT_DADOS_ABERTOS_CNPJ.pdf]

**Comment by tmcarmo** [comment]
Olá WanCaSil, vlw... isso vai ajudar MUITO... principalmente esse endereço do layout. já estou fazendo download para ajudar.
