### ISSUE TITLE
Atualização de Dados

### ISSUE THREAD

**Issue by matewf** [georgevbsantiago/qsacnpj#7]
Olá George,

Primeiro parabéns pelo trabalho e disponibilização.

Estou tentando apoiar minha esposa em um projeto de mestrado e para isso ela precisa acessar os dados atualizados dos CNPJ. Li todo seu trabalho aqui e não entendi totalmente como rodar estes dados, pode nos ajudar? há uma nova atualização depois da última que você disponibilizou aqui. Obrigado, Att, Mateus

**Comment by georgevbsantiago** [comment]
Olá, não entendi qual seria a sua dúvida. As instruções de como usar o código estão no README.

Ademais, se o pacote é importante para você, por favor, deixe um comentário no tópico: [Por que a base de dados do CNPJ é importante para você?](https://github.com/georgevbsantiago/qsacnpj/issues/4)
