### ISSUE TITLE
erro no trata_arquivo_txt

### ISSUE THREAD

**Issue by nicolasflorencio** [georgevbsantiago/qsacnpj#8]
Boa tarde ao tentar gerar bd da o seguite erro :
[1] "Iniciando o tratamento e consolidação dos dados do CNPJ. Esse processo pode levar entre 4h a 5h, dependenndo da configuração do computador!"
 Error in tratar_arquivo_txt(arquivo_txt, localizar_cnpj, n_lines, armazenar) : 
  não foi possível encontrar a função "tratar_arquivo_txt" 

como posso resolver !?

**Comment by georgevbsantiago** [comment]
Não sei como você está estruturando o seu código.
Por gentileza, siga as instruções que coloquei no README. 

Ademais, se o pacote é importante para você, por favor, deixe um comentário no tópico: [Por que a base de dados do CNPJ é importante para você?](https://github.com/georgevbsantiago/qsacnpj/issues/4)

**Comment by georgevbsantiago** [comment]
Não sei como você está estruturando o seu código.
Por gentileza, siga as instruções que coloquei no README. 

Ademais, se o pacote é importante para você, por favor, deixe um comentário no tópico: [Por que a base de dados do CNPJ é importante para você?](https://github.com/georgevbsantiago/qsacnpj/issues/4)
