### ISSUE TITLE
Atualização da Base da Receita

### ISSUE THREAD

**Issue by ChristianMatola** [georgevbsantiago/qsacnpj#9]
Boa tarde,

gostaria de saber quando será feita a atualização dos dados de CNPJ com a última q saiu.
Desde já grato e parabéns pelas informações,

Christian

**Comment by georgevbsantiago** [comment]
Olá, farei a atualização dos dados hoje. 
Ademais, se o pacote é importante para você, por favor, deixe um comentário no tópico: [Por que a base de dados do CNPJ é importante para você?](https://github.com/georgevbsantiago/qsacnpj/issues/4)
